version: '3'

services:
  servico-users:
    build: ./servico_users
    networks:
      - rede-gateway

  servico-orders:
    build: ./servico_orders
    networks:
      - rede-gateway
  api-gateway:
    build: ./gateway
    ports:
      - "8085:80" 
    depends_on:
      - servico-users
      - servico-orders
    networks:
      - rede-gateway

networks:
  rede-gateway: